### ISSUE TITLE
T265 will not connect to realsense viewer

### ISSUE THREAD

**Issue by amano001** [JetsonHacksNano/installLibrealsense#10]
Hello,

Just wanted to say that without your tutorials I would probably not have gotten this far!  But I have had issues trying to get the T265 to be seen on the TX2 (using your tutorials) and now tried it on my nano as well.  I get the same issue where it is detected in lsusb as 03e7:2150 which under dmesg is listed as Movidius.  I did a fresh install onto SD card of the Nano image, and followed your scripts, not sure what I am missing.  I have tried the camera directly connected to the nano, I have tried to a powered usb 3.0 hub and they both pop up with the same 03e7:2150.  But trying to run any of the samples and realsense viewer it does not detect it.  I did notice with your TX2 tutorial I got the D435 to show up at least as Intel Corp in lsusb but as USB 2.1(another issue I will tackle on your other github haha).  Forgot to add that I did have the T265 working on my windows PC.

Thanks!

**Comment by jmachuca77** [comment]
You need to add a flag to the cmake call to enable the T265, add-DBUILD_WITH_TM2=ON

**Comment by JetsonHacksNano** [comment]
Please try the later installLibrealsense.sh script which should handle this issue. If you encounter further problems, please open a new issue.
