### ISSUE TITLE
ReallSensee R200 SUPPORT ?

### ISSUE THREAD

**Issue by Tondy** [JetsonHacksNano/installLibrealsense#11]
Hello

Does this library support realsense r200 or any recommendation for other options to run inter; r200 camera on jetson nano.

**Comment by JetsonHacksNano** [comment]
This is for librealsense2 which is for the D4XX series and T265 tracking cameras. You will need to port librealsense to work with the r200.

**Comment by svanimisetti** [comment]
@TonderaiZR - did you find a way to get R200 to work on the latest Jetson Nano release (`Linux jetsonnano 4.9.253-tegra`)? If I use the `installLibrealsense.sh` script and try to run the `realsense-viewer`, I cannot find the R200 listed in the devices. However, I do see the following INFO message on the terminal.

> INFO [548137283600] (context.cpp:382) Found 2 RealSense devices (mask 0xfe)

I am guessing that old librealsense (v1.x) cannot be installed using binary repository and has to be built from source? If this is the case, have you figured out how? If yes, can you please share the steps on getting my R200 working with Jetson Nano.

**Comment by svanimisetti** [comment]
After digging a litte, I found [instructions ](https://github.com/IntelRealSense/librealsense/blob/v1.12.1/doc/installation.md) on installing legacy librealsense (v1.12.1) that apparently supports R200. However, the build process is giving errors on 4.9.253-tegra. Perhaps, I will open a separate issue for this.

**Comment by TonderaiZR** [comment]
Hi Svanimiseti

Did you firmware update the realsense?

**Comment by svanimisetti** [comment]
@TonderaiZR - Thanks for a quick reply! No - I did not update the firmware on R200. Is this a necessary step? I don't have experience updating firmware on Linux - so I may try this from Windows.

**Comment by TonderaiZR** [comment]
@svanimisetti  Its worth checking if the versions are compatible.
