### ISSUE TITLE
Script eaten all mySD free space

### ISSUE THREAD

**Issue by FPSychotic** [JetsonHacksNano/installLibrealsense#13]
hi, after install the script it used I dont know 20GB? of my memory. Is this right with the script, ? In my other boards it doesnt happen.Some fix to recover my space?

**Comment by aKutluozen** [comment]
I am also having the same issue, as of now I have about 2 GB left, and the space keeps getting smaller, the script is still running. Hope it shrinks at some point. Or, maybe is there any duplicate files that we can delete after this installation finishes?

**Comment by FPSychotic** [comment]
It ruined the instalation as even after free 5gb of ros2, the second script leaved 0mb in the sd card. Im new in linux, but is out of my understanding how the 30mb of a module can be converted in 25gb, Im curious really

**Comment by ondeviceai** [comment]
Hi @FPSychotic ,
Have you a solution to recover your space. I have same issue here

**Comment by FPSychotic** [comment]
> Hi @FPSychotic ,
> Have you a solution to recover your space. I have same issue here

If I remember, I used a bigger SD card, 64Gb and after installation I think I removed the kernel files of the build, I dont remember the folder, but I think is something like user/local/arch64/boot  I cant tell you now exactly, I get the things, but because I just do one time, I tend to forget fast.

**Comment by JetsonHacksNano** [comment]
Doing a kernel build is no longer necessary in the newer releases. Please open another issue if you encounter further problems.
