### ISSUE TITLE
Outdated Version of Librealsense

### ISSUE THREAD

**Issue by vizzbee** [JetsonHacksNano/installLibrealsense#19]
Hey JetsonHacks,

Big Fan of your work. 
I was installing librealsense in Jetson Nano for integration with ROS. On running catkin_make, build files and binaries of realsense were not accepted. On deep inspection, the version that your script installs is 2.24 while ros needs 2.25, which is the latest version. Kindly update

**Comment by JetsonHacksNano** [comment]
The version of librealsense and librealsenseROS are rarely in sync. You will need to install the corresponding matching version of each.
