### ISSUE TITLE
"buildPatchedKernel.sh" is functional ?

### ISSUE THREAD

**Issue by RitwikSaikia** [JetsonHacksNano/installLibrealsense#2]
The build ends quickly with following output

```
Jetson Model: jetson-nano
Jetson L4T: 32.1.0
Through OK
```

https://github.com/JetsonHacksNano/installLibrealsense/blob/master/buildPatchedKernel.sh#L97

There is an exit, just before kernel compilation, is it not required in case of Nano ?

**Comment by JetsonHacksNano** [comment]
Changed the name too patchUbuntu. Should be fixed, try it out.
