### ISSUE TITLE
run buildlibrealsense.sh get the "version mismatch!" error

### ISSUE THREAD

**Issue by Andrew5c** [JetsonHacksNano/installLibrealsense#28]
I run the installlibrealsense.sh first,and run the buildlibrealsense.sh .but the result is "version mismatch!",what is the problem?what can I do?
it will be very thanks for a reply.

**Comment by droter** [comment]
If you have ran the script before you will need to manually delete the librealsense folder in the home directory.

**Comment by Andrew5c** [comment]
> If you have ran the script before you will need to manually delete the librealsense folder in the home directory.

Thanks for your help, but you mean that I should delete the librealsense folder manually ,then run the script ?

**Comment by droter** [comment]
Yes.

**Comment by JetsonHacksNano** [comment]
Closing since there has not been an activity for a while.

**Comment by HappySamuel** [comment]
Hi @JetsonHacksNano 

I also faced the similar issue, what shall i do?  I have tried to remove the `librealsense` folder that at `$HOME` directory, but the result remains the same. I still being thrown with `version mismatch` error

```
agx-orin@agx-orin:~/Downloads/installLibrealsense$ ./buildLibrealsense.sh -v 2.55.1
Build with CUDA: true
Librealsense Version: 2.55.1

Please make sure that no RealSense cameras are currently attached

Press any key to continue
Cloning librealsense
Cloning into 'librealsense'...
remote: Enumerating objects: 143792, done.
remote: Counting objects: 100% (1404/1404), done.
remote: Compressing objects: 100% (598/598), done.
remote: Total 143792 (delta 920), reused 1210 (delta 792), pack-reused 142388 (from 1)
Receiving objects: 100% (143792/143792), 258.67 MiB | 16.00 MiB/s, done.
Resolving deltas: 100% (105444/105444), done.

==== librealsense Version Mismatch! =============

The installed version of librealsense is not current enough for these scripts.
This script needs librealsense tag version: 2.55.1 but it is not available.
Please upgrade librealsense or remove the librealsense folder before attempting to install again.

agx-orin@agx-orin:~/Downloads/installLibrealsense$ 
```

Best
Samuel
