### ISSUE TITLE
execution installLibrealsense.sh failed

### ISSUE THREAD

**Issue by CitronSeason** [JetsonHacksNano/installLibrealsense#29]
I attempt to run installlibrealsense.sh into jetson.
but the result is
`gpg: keyserver receive failed: No data.`
and coudn't completed.
Maybe, recv-key is different of gpgkey.
So I import the correct key(C8B3A55A6F3EFCDE) myself

As a result, the execution of installLibrealsense.sh was successful.
Is the apt-key adv command in installLibrealsense.sh is the correct???

**Comment by JetsonHacksNano** [comment]
The keys have been updated in v1.1.
