### ISSUE TITLE
ISO C and ISO C++ warnings when building realsense

### ISSUE THREAD

**Issue by jorgemiar** [JetsonHacksNano/installLibrealsense#34]
I'm trying to build librealsense 2.33.1 with CUDA on (I modified the script to target 2.33.1). When I run it and it starts building, I keep getting warnings such as: 

```
/home/unmnd/librealsense/third-party/glfw/src/x11_init.c:613:42: warning: ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]
         _glfw.x11.xcursor.ImageDestroy = (PFN_XcursorImageDestroy)

```
or
```
/usr/include/libusb-1.0/libusb.h:1263:4: warning: ISO C++ forbids zero-size array ‘iso_packet_desc’ [-Wpedantic]
  [0] /* non-standard, but usually working code */
    ^

```
What is causing these errors? Should I try building without CUDA? Change some of the build flags?

**Comment by JetsonHacksNano** [comment]
These are warnings, not errors. These issues are from the librealsense repository, not this one.
