### ISSUE TITLE
Jetson Nano use JetPack 4.4 ./buildLibrealsense.sh Error 

### ISSUE THREAD

**Issue by seed00** [JetsonHacksNano/installLibrealsense#36]
Is installLibrealsense is not suport  JetPack 4.4??

CMAKE VERSION:cmake-3.17

It's use Jetson Nano use JetPack 4.4  installl ./buildLibrealsense.sh Error

Configuring Make system
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Internet connection identified
CMake Deprecation Warning at CMakeLists.txt:10 (MESSAGE):
  FORCE_LIBUVC, FORCE_WINUSB_UVC and ANDROID_USB_HOST_UVC are deprecated                                                                    , use
  FORCE_RSUSB_BACKEND instead

-- Info: REALSENSE_VERSION_STRING=2.31.0
-- Setting Unix configurations
-- Info: Building with CUDA requires CMake v3.8+
CMake Error at /usr/local/share/cmake-3.17/Modules/CMakeDetermineCUDACom                                                                    piler.cmake:25 (message):
  Could not find compiler set in environment variable CUDACXX:

  /usr/local/cuda-10.0/bin/nvcc.

Call Stack (most recent call first):
  CMake/cuda_config.cmake:3 (project)
  CMake/global_config.cmake:61 (include)
  CMakeLists.txt:44 (global_set_flags)

CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/jetson/librealsense/build/CMakeFiles/CMakeOutput.log".
Building librealsense, headers, tools and demos
make: *** No targets specified and no makefile found.  Stop.

real    0m0.005s
user    0m0.000s
sys     0m0.000s
librealsense did not build
Retrying ...
make: *** No targets specified and no makefile found.  Stop.

real    0m0.005s
user    0m0.004s
sys     0m0.000s
librealsense did not successfully build
Please fix issues and retry build

**Comment by geoffawill** [comment]
Change the Cuda location to /usr/local/cuda-10.2/bin/nvcc

**Comment by JetsonHacksNano** [comment]
The new scripts should take care of this. v1.1. If you encounter further issues, please reopen.
