### ISSUE TITLE
realsense-viewer can't find realsense L515

### ISSUE THREAD

**Issue by gfjiyue** [JetsonHacksNano/installLibrealsense#37]
**Describe the issue**
Librealsense was successfully installed following the guide.
However, the realsense-viewer can't find realsense L515.
And there is a warning said "Multiple realsense udev-rules were found".

**NVIDIA Jetson Hardware**
 Jetson Nano

**L4T / JetPack Version**
latest on 2020/09/22

** Software version**
None.

**To Reproduce**
realsense-viewer

**Expected behavior**
realsense-viewer works for realsense L515.

**Comment by JetsonHacksNano** [comment]
You need to check the installed version of librealsense. The new scripts should install the most current version. Please reopen if you encounter further issues.
