### ISSUE TITLE
D435i not recongized

### ISSUE THREAD

**Issue by kat-mcg-lin** [JetsonHacksNano/installLibrealsense#7]
How can we get the D435i to work properly?? I know the notes say it won't get recongized, but there must be some way?! Are there any other external patches or something? Jetson Hacks made a video about connecting a nano to a D435i and they got it to work there.... what did they do that isn't included in the git?!

**Comment by JetsonHacksNano** [comment]
It is difficult to tell from your description the issue you are experiencing. 
The notes were not updated at the time of the release of the video, everything should work. 
Is the firmware recent enough on your camera?
https://downloadcenter.intel.com/download/28573/Latest-Firmware-for-Intel-RealSense-D400-Product-Family?product=128255

**Comment by kat-mcg-lin** [comment]
Hi! That's peculiar then that mine doesn't work. I also just tried updating the camera to the latest FW on my host computer, then plugged it back into the jetson nano and still nothing :(

**Comment by kat-mcg-lin** [comment]
I just re-flashed the SD card, and re-installed everything by following your video exactly and the same error persists, no device is recognized when the D435i is plugged in, but works just fine for the T256

**Comment by JetsonHacksNano** [comment]
Just for reference, did you:

1. Use a swapfile
2. Compile with CUDA support

**Comment by kat-mcg-lin** [comment]
yes to both

**Comment by JetsonHacksNano** [comment]
What is the result of:
$ lsusb -t
and are you using a USB hub?

**Comment by kat-mcg-lin** [comment]
output:
Bus 002 Device 004: ID 8086:0b3a Intel Corp. 
Bus 002 Device 002: ID 0bda:0411 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 413c:2113 Dell Computer Corp. 
Bus 001 Device 003: ID 0000:0538  
Bus 001 Device 002: ID 0bda:5411 Realtek Semiconductor Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I am running from the micro SD card (64BG) and not using a USB hub, just the available USB ports on the device

**Comment by kat-mcg-lin** [comment]
oh oops- that's the result of just lsusb

the results of lsusb -t are as follows:

/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=tegra-xusb/4p, 5000M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=tegra-xusb/5p, 480M
    |__ Port 2: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 1: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 2: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 2: Dev 4, If 1, Class=Human Interface Device, Driver=usbhid, 1.5M

**Comment by JetsonHacksNano** [comment]
One more question, how are you powering the Jetson Nano? Are you using the MicroUSB connector, or powering it through the barrel jack?

**Comment by kat-mcg-lin** [comment]
the microUSB connector

**Comment by JetsonHacksNano** [comment]
That's probably the issue. I'm building up a system to test it out.

**Comment by JetsonHacksNano** [comment]
Ok, I think I located the problem and fixed it. You will need to download the new installLibrealsense repository (tagged version v0.8 as a marker for people later on). The offender was in patchUbuntu.sh.
There are a couple of ways to proceed. You can run patchUbuntu again (and skip over the requests to Revert the previously applied patches). Or, if you're less trusting like I am, you can  delete the directories /usr/src/kernel and /usr/src/hardware and run patchUbuntu.sh again from the installLibrealsense directory. Please let me know if this works.

**Comment by kat-mcg-lin** [comment]
This worked! Thank you!

I did as you said and deleted the directories then reran the patches.

thanks again for all your help!
