### ISSUE TITLE
No depth view

### ISSUE THREAD

**Issue by clahlou** [JetsonHacksNano/installLibrealsense#8]
After installing librealsense script with -c option on nano, running the patch script, and launching the realsense viewer app with Intel RealSense Depth Camera D435, I got many warning messages and no RGB module and no Depth stream under Stereo module.

Warning message from command line
19/05 23:20:40,537 WARNING [548239978096] (sensor.cpp:365) Unregistered Media formats : [ UYVY ]; Supported: [ GREY UYVY Y8I  Z16  ]
RealSense

App warning message
Current firmware version: 05.09.02.00
Minimal firmware version: 05.10.03.00

Error message when enabling Depth stream
Incomplete video frame detected/No  frames received

**Comment by JetsonHacksNano** [comment]
I believe that means that you need to upgrade the firmware on your RealSense camera. Please see: https://downloadcenter.intel.com/download/28573/Latest-Firmware-for-Intel-RealSense-D400-Product-Family?product=128255
