### ISSUE TITLE
Kernel Rebuild Effects

### ISSUE THREAD

**Issue by lesreaper** [JetsonHacksNano/installLibrealsense#9]
Does this kernel rebuild affect the I2C or SPI setups for the GPIO?

I'm having challenges with an I2C setup and tracing down the issue. Thanks!

**Comment by JetsonHacksNano** [comment]
Not that I know of. SPI is not enabled by default in a Jetson Nano, and is assigned in the device tree. It is difficult to diagnose the I2C issue based on your description.
